### PR TITLE
removed todo routes and movde the todo schema as a sub-document of lists

### PR DESCRIPTION
**Pull request by juanmi108**
fix for #32 and #13 

this commit contains BRANKING CHANGES. 

todos collection was removed. todos are now saved inside the lists as a sub document. with 2 properties, active and completed. 

```javascript
 todos: {active: [{duedate: Date, description: {type: String, required: true}, completed: {type: Boolean, default: false}}],
            completed: [{duedate: Date, description: {type: String, required: true}, completed: {type: Boolean, true: false}}]
        }
```

please test before merge

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/juanmi108/Super-Global-Hyper-Mega-Net-nosql/pull/37" target="_blank">ReviewNinja

**Comment by chappy2** [comment]
why completed and aktive? It wil make the view defnetly cleaner and improve performance.

**Comment by juanmi108** [comment]
was that a question or a compliment? :)

**Comment by chappy2** [comment]
First part was the question. Don't know if you saw the controller function for save todo. Its totally messy. The listView too. I really like to change that. i looks horrible.

**Comment by juanmi108** [comment]
the todos is divided in completed and active so that getting the active todos would be easier. getting the whole array is better than interating over all of them and asking if its completed or not. 

where is the controller for todo? I only found the service in /public/todo

**Comment by chappy2** [comment]
It doesn't have a controller and view. The servise is used in ListController.js

**Comment by juanmi108** [comment]
where comes this 'Todo' object comes from? 
https://github.com/juanmi108/Super-Global-Hyper-Mega-Net-nosql/blob/master/public/lists/listsController.js#L139

**Comment by chappy2** [comment]
From the Service. With ng resource its possible to create Todos for the Todos resource.

**Comment by juanmi108** [comment]
oh ok cool

**Comment by juanmi108** [comment]
ok ill change the todo part of the controller and commit it to this pr.

**Comment by chappy2** [comment]
ok

**Comment by juanmi108** [comment]
changed a lot. see the diff

**Pull request merged**
